"""Synthesised media fixtures.

Everything the mechanical stage is tested against is generated by `ffmpeg
-f lavfi` at test time. No binary fixture is committed: a webinar clip is large,
opaque, and impossible to review in a diff, and the properties these tests
assert (duration, resolution, where the silence is) are exactly the properties
lavfi lets us state up front.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from makeshorts.artifacts import Word, WordsDoc

FFMPEG = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"

requires_ffmpeg = pytest.mark.skipif(
    not Path(FFMPEG).exists(), reason="ffmpeg not installed"
)


def run_ffmpeg(args: list[str]) -> None:
    proc = subprocess.run(
        [FFMPEG, "-nostdin", "-hide_banner", "-y", *args],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:  # pragma: no cover - only on a broken ffmpeg
        raise RuntimeError(f"fixture generation failed:\n{proc.stderr[-2000:]}")


@pytest.fixture(scope="session")
def av_file(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """6s, 320x240, 30fps, one audio channel, silent from 2.0s to 4.0s.

    The silent window is produced by gating the sine rather than concatenating,
    so the file has one continuous audio stream and the silence is genuinely
    mid-file.
    """
    out = tmp_path_factory.mktemp("media") / "av.mp4"
    run_ffmpeg(
        [
            "-f", "lavfi", "-i", "testsrc2=size=320x240:rate=30:duration=6",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=6:sample_rate=44100",
            "-filter_complex", "[1:a]volume=enable='between(t,2,4)':volume=0,pan=mono|c0=c0[a]",
            "-map", "0:v", "-map", "[a]",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            "-t", "6", str(out),
        ]
    )
    return out


@pytest.fixture(scope="session")
def slides_view_file(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A second view of the same 6s recording: different resolution, same clock.

    This is the shape a Zoom cloud recording exports -- several renders of one
    meeting, frame-aligned and sharing an audio track, at whatever resolution
    each view happened to need. `av_file` is the camera view of the same six
    seconds.
    """
    out = tmp_path_factory.mktemp("media") / "slides.mp4"
    run_ffmpeg(
        [
            "-f", "lavfi", "-i", "smptebars=size=480x270:rate=30:duration=6",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=6:sample_rate=44100",
            "-filter_complex", "[1:a]volume=enable='between(t,2,4)':volume=0,pan=mono|c0=c0[a]",
            "-map", "0:v", "-map", "[a]",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            "-t", "6", str(out),
        ]
    )
    return out


@pytest.fixture(scope="session")
def audio_only_file(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The audio-only export that arrives beside the video views."""
    out = tmp_path_factory.mktemp("media") / "audio.m4a"
    run_ffmpeg(
        [
            "-f", "lavfi", "-i", "sine=frequency=440:duration=6:sample_rate=44100",
            "-c:a", "aac", "-t", "6", str(out),
        ]
    )
    return out


@pytest.fixture(scope="session")
def video_only_file(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """4s of video with no audio stream at all -- screen recordings arrive this
    way more often than anyone expects."""
    out = tmp_path_factory.mktemp("media") / "mute.mp4"
    run_ffmpeg(
        [
            "-f", "lavfi", "-i", "testsrc2=size=640x360:rate=25:duration=4",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an",
            "-t", "4", str(out),
        ]
    )
    return out


def make_words(*specs: tuple[str, float, float]) -> WordsDoc:
    """`WordsDoc` from `(text, start, end)` triples, with sentence flags applied
    by the real segmenter."""
    from makeshorts.prepare.transcribe import mark_sentence_boundaries

    words = [Word(text=t, start=s, end=e) for t, s, e in specs]
    return WordsDoc(model="test", language="en", words=mark_sentence_boundaries(words))


def evenly_timed(text: str, *, start: float = 0.0, per_word: float = 0.4) -> WordsDoc:
    """A WordsDoc from a sentence, one word every `per_word` seconds."""
    specs = []
    t = start
    for token in text.split():
        specs.append((token, round(t, 3), round(t + per_word * 0.8, 3)))
        t += per_word
    return make_words(*specs)
